name: qkbc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12,<3.13
  - pip  
  - matplotlib
  - notebook
  - numpy
  - qiskit>=2.0
  - pandas
  - tqdm
  - pylatexenc
  - msal
  - seaborn
  - scipy
  - scikit-learn
  - networkx
  - tqdm
  - pip:
    - qiskit-ibm-runtime>=0.37.0, <=0.38.0
    - qiskit-aer>=0.17.0, <=0.18
    - openpyxl>=3.1.4
